---
title: Stakeholder
description: Business or technical leaders who define success criteria.
id: "PER_Stakeholder"
---
mindmap
  PER_Stakeholder((Stakeholder))
    Role
      Influencer
    Description
      Business or technical leaders who define success criteria for the project.
    Goals
      Ensure project success
      Minimize overhead
      Drive strategy
      Maintain architecture integrity
