---
id: "REQ_Group"
title: Requirements
description: Core system capabilities.
uplink: "PER_Group"
entities:
  - id: "REQ_Functional"
    uplink: "PER_EndUser"
  - id: "REQ_NonFunctional"
    uplink: "PER_Stakeholder"
---

requirementDiagram

    requirement Functional {
        id: "REQ_Functional"
        text: "The system shall provide X..."
        risk: Low
        verifymethod: Test
    }

    requirement Feature_A {
        id: "REQ_FeatA"
        text: "Specific feature detail"
        risk: Low
        verifymethod: Test
    }

    requirement Non_Functional {
        id: "REQ_NonFunctional"
        text: "Non-Functional Requirements"
        risk: Low
        verifymethod: Test
    }

    Functional -contains-> Feature_A